compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  subscriptions-transport-ws@*:
    peerDependenciesMeta:
      "@types/ws":
        optional: true

  "@mermaid-js/mermaid-cli@*":
    peerDependenciesMeta:
      puppeteer:
        optional: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
