name: Base Test Workflow

on:
  workflow_call:
    inputs:
      package:
        description: Name of the package that should be tested
        type: string
        required: true
      testcommand:
        description: Command to execute, usually test or posttest
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      JEST_MAX_WORKERS: 4
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: localhost
      PGVERSION: ${{ matrix.postgres-version}}
      TEST_SIMPLIFY_DATABASE_URL: postgres://postgres:postgres@localhost:5432/pg_simplify_inflectors
      TERM: xterm
      FORCE_COLOR: 1
      NODE_OPTIONS: "--max-old-space-size=4096 --disable-proto=delete"
      NODE_ENV: test

    strategy:
      fail-fast: false
      matrix:
        postgres-version: [12, 17] #, 11, 13, 14, 15]
        node-version: [22.x]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - "0.0.0.0:5432:5432"
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5 --name postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Configure PostgreSQL
        run: |
          cat .github/workflows/ci/docker-entrypoint-initdb.d/010-enable_wal.sh | docker exec -i postgres bash
          cat .github/workflows/ci/docker-entrypoint-initdb.d/020-wal2json.sh | docker exec -i postgres bash
          cat .github/workflows/ci/docker-entrypoint-initdb.d/030-setup.sh | docker exec -i postgres bash
          echo "cat /var/lib/postgresql/data/postgresql.conf" | docker exec -i postgres bash
          docker restart postgres
      - name: Install pg_dump
        run: |
          sudo mkdir -p /usr/share/keyrings
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /usr/share/keyrings/pgdg-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/pgdg-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null
          sudo apt-get update
          sudo apt-get -yqq install postgresql-client-${{ matrix.postgres-version }}

      - run: yarn --immutable

      - name: "Wait for postgres"
        run: node .github/wait-for-postgres.js

      - name: "Docker logs postgres"
        run: docker logs "${{ job.services.postgres.id }}"

      - name: "Build"
        run: yarn build

      - name: "Prepack"
        run: yarn workspaces foreach --verbose --parallel --topological --recursive --from '${{ inputs.package }}' run prepack

      - name: "Test Project"
        run: yarn run pretest && yarn workspaces foreach --verbose --parallel --worktree --jobs 2 --from '${{ inputs.package }}' run ${{ inputs.testcommand }}
