name: Test

on: [push, pull_request]

jobs:
  dataplan_pg:
    name: "@dataplan/pg tests"
    uses: ./.github/workflows/test-base.yml
    with:
      package: "@dataplan/pg"
      testcommand: "test"

  postgraphile_jest:
    name: PostGraphile jest tests
    uses: ./.github/workflows/test-base.yml
    with:
      package: "postgraphile"
      testcommand: "test:jest"

  postgraphile_schema_exports:
    name: PostGraphile schema export tests
    uses: ./.github/workflows/test-base.yml
    with:
      package: "postgraphile"
      testcommand: "test:schema-exports"

  postgraphile_export_typeDefs:
    name: PostGraphile tests (exported as typeDefs)
    uses: ./.github/workflows/test-base.yml
    with:
      package: "postgraphile"
      testcommand: "test:operations-exports:typeDefs"

  postgraphile_export_graphqljs:
    name: PostGraphile tests (exported as graphql-js)
    uses: ./.github/workflows/test-base.yml
    with:
      package: "postgraphile"
      testcommand: "test:operations-exports:graphql-js"

  small_packages:
    name: Small package tests
    uses: ./.github/workflows/test-base.yml
    with:
      package: "{pg-sql2,tamedevil,@grafserv/persisted,@graphile/lru,@graphile/simplify-inflection,@localrepo/grafast-bench,@localrepo/grafast-website,grafast,graphile,graphile-config,graphile-utils,jest-serializer-graphql-schema,pg-introspection,grafserv}"
      testcommand: "test"
